version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  my1: up-it-test/orb_1@dev:first
executors:
  my-ex: my1/py_3_7_9
commands:
  git_pull : my1/git_pull_pipelies
  it_test : my1/run_integration_test

jobs:
  matillion_shared_jobs: 
    executor: my-ex
    steps:
      - git_pull :
          matillion_url: "https://matillion-dev.dev.rotw.uplight.io"
          project_name: "avangrid_poc"
          git_url: "https://github.com/Uplight-Inc/up_matillion_shared_jobs.git"
          branch_name: "main"
      - it_test :
          test_suite_command: "-m matillion_shared_job"
          profile_key_name: "Matillion_shared_jobs"

workflows:
  version: 2

  nightly:
    triggers:
      - schedule:
          cron: "30 19 * * *"
          filters:
            branches:
              only:
                  - master
                  - main
    jobs:
      - matillion_shared_jobs:
          context:
              - up_matillion_shared_jobs

  on-commit:
    jobs:
      - matillion_shared_jobs:
          context:
              - up_matillion_shared_jobs
          filters:
              branches:
                only:
                  - master
                  - main
